# Generated by Django 5.2.8 on 2025-11-26 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=200)),
                ('tgl_terbit', models.DateField()),
                ('nama_pengarang', models.CharField(max_length=100)),
                ('nama_penerbit', models.CharField(max_length=100)),
                ('tersedia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('tgl_daftar', models.DateField(auto_now_add=True)),
                ('foto_peminjam', models.ImageField(blank=True, null=True, upload_to='foto_peminjam/')),
                ('status_peminjam', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pinjam', models.CharField(max_length=20, unique=True)),
                ('tgl_pesan', models.DateField(auto_now_add=True)),
                ('tgl_ambil', models.DateField(blank=True, null=True)),
                ('tgl_wajibkembali', models.DateField(blank=True, null=True)),
                ('tgl_kembali', models.DateField(blank=True, null=True)),
                ('status_pinjam', models.CharField(choices=[('DIPROSES', 'Diproses'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('SELESAI', 'Selesai')], default='DIPROSES', max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_verifikator', to=settings.AUTH_USER_MODEL)),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.peminjam')),
            ],
        ),
        migrations.CreateModel(
            name='DetilPeminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buku')),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.peminjaman')),
            ],
        ),
    ]
