# Generated by Django 5.2.8 on 2025-11-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='tgl_input',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
